# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3.3-node-browsers

    environment:
      - APP_DEBUG: true
      - APP_ENV: testing

    working_directory: ~/repo/

    steps:
      - checkout:
          path: ~/repo

      - run: sudo apt update
      - run: sudo apt upgrade
      - run: sudo apt install -y git libgmp3-dev libmcrypt-dev libxml2-dev libmcrypt-dev default-mysql-client
      - run: sudo ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h
      - run: sudo docker-php-ext-install gmp xml mbstring pdo tokenizer dom pdo_mysq

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: sudo curl -sS https://getcomposer.org/installer | php -- --filename=composer
      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: php artisan clear-compiled

      # run tests with phpunit or codecept
      - run: mv ./tests/.env.circleci ./tests/.env
      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/codecept build
      - run: ./vendor/bin/codecept run
